import { defineArea } from '../area'

export default defineArea({
  'ob5.banner': ['初期セットアップが未完了です。一部の機能は、完了すると使えるようになります。', 'Initial setup is incomplete. Some features become available once you finish it.', '초기 설정이 완료되지 않았습니다. 완료하면 일부 기능을 사용할 수 있습니다.', 'Die Ersteinrichtung ist unvollständig. Einige Funktionen sind nach Abschluss verfügbar.', 'La configuration initiale n’est pas terminée. Certaines fonctions seront disponibles une fois terminée.', 'La configuración inicial está incompleta. Algunas funciones estarán disponibles al terminarla.', '初始设置尚未完成。完成后即可使用部分功能。', 'A configuração inicial está incompleta. Alguns recursos ficam disponíveis após concluí-la.', 'La configurazione iniziale non è completa. Alcune funzioni saranno disponibili al termine.', 'Начальная настройка не завершена. Часть функций станет доступна после её завершения.'],
  'ob5.go': ['セットアップを続ける', 'Continue setup', '설정 계속하기', 'Einrichtung fortsetzen', 'Continuer la configuration', 'Continuar la configuración', '继续设置', 'Continuar a configuração', 'Continua la configurazione', 'Продолжить настройку'],
  'ob5.survey': ['回答するには、先に初期セットアップを完了してください。', 'Please finish the initial setup before submitting an answer.', '답변하려면 먼저 초기 설정을 완료해 주세요.', 'Bitte schließen Sie zuerst die Ersteinrichtung ab, um zu antworten.', 'Terminez d’abord la configuration initiale pour répondre.', 'Termina primero la configuración inicial para responder.', '请先完成初始设置后再提交回答。', 'Conclua a configuração inicial antes de responder.', 'Completa prima la configurazione iniziale per rispondere.', 'Чтобы ответить, сначала завершите начальную настройку.'],
  'ob5.lockT': ['初期セットアップを完了してください', 'Finish the initial setup', '초기 설정을 완료해 주세요', 'Bitte schließe die Einrichtung ab', 'Terminez la configuration initiale', 'Completa la configuración inicial', '请先完成初始设置', 'Conclua a configuração inicial', 'Completa la configurazione iniziale', 'Завершите начальную настройку'],
  'ob5.lockD': ['アンケートに回答するには、セットアップの完了が必要です。数分で終わります。', 'Complete the setup to answer this survey. It only takes a few minutes.', '설문에 답하려면 설정을 완료해야 합니다. 몇 분이면 끝나요.', 'Schließe die Einrichtung ab, um an der Umfrage teilzunehmen. Das dauert nur wenige Minuten.', 'Terminez la configuration pour répondre au sondage. Cela ne prend que quelques minutes.', 'Completa la configuración para responder la encuesta. Solo toma unos minutos.', '完成设置后才能参与问卷，只需几分钟。', 'Conclua a configuração para responder à pesquisa. Leva apenas alguns minutos.', 'Completa la configurazione per rispondere al sondaggio. Bastano pochi minuti.', 'Завершите настройку, чтобы ответить на опрос. Это займёт пару минут.'],
  'ob5.lockL': ['回答するにはログインが必要です', 'Log in to answer this survey', '설문에 답하려면 로그인이 필요합니다', 'Zum Antworten ist eine Anmeldung nötig', 'Connectez-vous pour répondre', 'Inicia sesión para responder', '请登录后参与问卷', 'Entre para responder', 'Accedi per rispondere', 'Войдите, чтобы ответить'],
  'ob5.login': ['ログイン', 'Log in', '로그인', 'Anmelden', 'Se connecter', 'Iniciar sesión', '登录', 'Entrar', 'Accedi', 'Войти'],
  'ob5.lockP': ['このページを使うには、セットアップの完了が必要です。数分で終わります。','Complete the setup to use this page. It only takes a few minutes.','이 페이지를 사용하려면 설정을 완료해야 합니다. 몇 분이면 끝나요.','Schließe die Einrichtung ab, um diese Seite zu nutzen. Das dauert nur wenige Minuten.','Terminez la configuration pour utiliser cette page. Cela ne prend que quelques minutes.','Completa la configuración para usar esta página. Solo toma unos minutos.','完成设置后才能使用此页面，只需几分钟。','Conclua a configuração para usar esta página. Leva apenas alguns minutos.','Completa la configurazione per usare questa pagina. Bastano pochi minuti.','Завершите настройку, чтобы пользоваться этой страницей. Это займёт пару минут.'],
})
