import { defineArea } from '../area'

export default defineArea({
  'ob3.emT': ['メールアドレスを登録', 'Register your email', '이메일 주소 등록', 'E-Mail-Adresse registrieren', 'Enregistrer votre e-mail', 'Registrar tu correo', '注册邮箱地址', 'Cadastrar seu e-mail', 'Registra la tua email', 'Укажите адрес эл. почты'],
  'ob3.emD': ['重要なお知らせや通知の受信に必要です。登録するまでサービスはご利用いただけません。', 'Needed for important notices and notifications. The service is unavailable until you register.', '중요 공지와 알림 수신에 필요합니다. 등록 전에는 서비스를 이용할 수 없습니다.', 'Für wichtige Mitteilungen nötig. Der Dienst ist erst nach der Registrierung nutzbar.', 'Nécessaire pour les avis importants. Le service est indisponible tant que ce n’est pas fait.', 'Necesario para avisos importantes. El servicio no estará disponible hasta registrarlo.', '用于接收重要通知。注册之前无法使用本服务。', 'Necessário para avisos importantes. O serviço fica indisponível até o cadastro.', 'Necessaria per gli avvisi importanti. Il servizio non è disponibile finché non la registri.', 'Нужен для важных уведомлений. Пока адрес не указан, сервис недоступен.'],
  'ob3.emGo': ['メールを登録する', 'Register email', '이메일 등록하기', 'E-Mail registrieren', 'Enregistrer l’e-mail', 'Registrar correo', '注册邮箱', 'Cadastrar e-mail', 'Registra email', 'Указать почту'],
  'ob3.emOk': ['登録済みです', 'Already registered', '등록되었습니다', 'Bereits registriert', 'Déjà enregistré', 'Ya registrado', '已注册', 'Já cadastrado', 'Già registrata', 'Уже указан'],
  'ob3.xReq': ['サービスのご利用にはX連携が必須です。連携するまで他の機能は使えません。', 'X linking is required to use the service. Other features are unavailable until you link.', '서비스 이용에는 X 연동이 필수입니다. 연동 전에는 다른 기능을 쓸 수 없습니다.', 'Für die Nutzung ist die X-Verknüpfung Pflicht. Bis dahin sind andere Funktionen gesperrt.', 'La liaison X est obligatoire. Les autres fonctions sont bloquées jusque-là.', 'Vincular X es obligatorio. Las demás funciones no estarán disponibles hasta hacerlo.', '使用本服务必须关联 X。关联之前无法使用其他功能。', 'A vinculação do X é obrigatória. Outras funções ficam bloqueadas até vincular.', 'Il collegamento di X è obbligatorio. Le altre funzioni sono bloccate finché non lo fai.', 'Для использования сервиса нужна привязка X. До этого другие функции недоступны.'],
  'ob3.req': ['必須', 'Required', '필수', 'Pflicht', 'Obligatoire', 'Obligatorio', '必填', 'Obrigatório', 'Obbligatorio', 'Обязательно'],
})
