import { defineArea } from '../area'

export default defineArea({
  'ob4.tmT': ['利用規約への同意', 'Terms of Service', '이용약관 동의', 'Nutzungsbedingungen', 'Conditions d’utilisation', 'Términos de servicio', '同意服务条款', 'Termos de uso', 'Termini di servizio', 'Условия использования'],
  'ob4.tmD': ['ご利用には、利用規約とプライバシーポリシーへの同意が必要です。', 'You must agree to the Terms of Service and Privacy Policy to use the service.', '이용하려면 이용약관과 개인정보 처리방침에 동의해야 합니다.', 'Zur Nutzung musst du den Nutzungsbedingungen und der Datenschutzerklärung zustimmen.', 'Vous devez accepter les conditions d’utilisation et la politique de confidentialité.', 'Debes aceptar los términos de servicio y la política de privacidad.', '使用本服务需同意服务条款和隐私政策。', 'É necessário concordar com os Termos de uso e a Política de privacidade.', 'Per usare il servizio devi accettare i Termini e l’Informativa sulla privacy.', 'Для использования необходимо принять условия и политику конфиденциальности.'],
  'ob4.tmTerms': ['利用規約', 'Terms of Service', '이용약관', 'Nutzungsbedingungen', 'Conditions d’utilisation', 'Términos de servicio', '服务条款', 'Termos de uso', 'Termini di servizio', 'Условия использования'],
  'ob4.tmPolicy': ['プライバシーポリシー', 'Privacy Policy', '개인정보 처리방침', 'Datenschutzerklärung', 'Politique de confidentialité', 'Política de privacidad', '隐私政策', 'Política de privacidade', 'Informativa sulla privacy', 'Политика конфиденциальности'],
  'ob4.tmCheck': ['を読み、同意します', '— I have read and agree', '을(를) 읽고 동의합니다', '— gelesen und akzeptiert', '— j’ai lu et j’accepte', '— he leído y acepto', '— 我已阅读并同意', '— li e concordo', '— ho letto e accetto', '— прочитал(а) и согласен(на)'],
  'ob4.pbT': ['公開設定', 'Visibility', '공개 설정', 'Sichtbarkeit', 'Visibilité', 'Visibilidad', '公开设置', 'Visibilidade', 'Visibilità', 'Видимость'],
  'ob4.pbD': ['あなたのページを他の人に見せるか選びます。あとから設定で変更できます。', 'Choose whether others can see your page. You can change it later in Settings.', '다른 사람에게 내 페이지를 보여줄지 선택하세요. 나중에 설정에서 바꿀 수 있습니다.', 'Lege fest, ob andere deine Seite sehen. Später in den Einstellungen änderbar.', 'Choisissez si les autres voient votre page. Modifiable plus tard dans les réglages.', 'Elige si otros pueden ver tu página. Puedes cambiarlo luego en Ajustes.', '选择是否让他人查看你的页面，之后可在设置中更改。', 'Escolha se outras pessoas podem ver sua página. Você pode mudar depois nas configurações.', 'Scegli se gli altri possono vedere la tua pagina. Modificabile poi nelle impostazioni.', 'Выберите, будет ли ваша страница видна другим. Это можно изменить позже в настройках.'],
  'ob4.pbOn': ['公開する', 'Public', '공개', 'Öffentlich', 'Public', 'Público', '公开', 'Público', 'Pubblico', 'Публичный'],
  'ob4.pbOnD': ['固有URLを知っている人が実績を見られます。', 'Anyone with your URL can see your records.', '고유 URL을 아는 사람이 기록을 볼 수 있습니다.', 'Jeder mit deiner URL kann deine Einträge sehen.', 'Toute personne ayant votre URL voit vos publications.', 'Cualquiera con tu URL puede ver tus registros.', '知道专属链接的人可以查看你的记录。', 'Qualquer pessoa com seu URL vê seus registros.', 'Chiunque abbia il tuo URL può vedere le tue registrazioni.', 'Любой, у кого есть ваша ссылка, видит ваши записи.'],
  'ob4.pbOff': ['非公開にする', 'Private', '비공개', 'Privat', 'Privé', 'Privado', '不公开', 'Privado', 'Privato', 'Приватный'],
  'ob4.pbOffD': ['自分だけが閲覧できます。', 'Only you can see it.', '나만 볼 수 있습니다.', 'Nur du kannst es sehen.', 'Vous seul(e) pouvez le voir.', 'Solo tú puedes verlo.', '仅自己可见。', 'Somente você pode ver.', 'Solo tu puoi vederlo.', 'Видно только вам.'],
  'ob4.prT': ['プロフィールの確認', 'Check your profile', '프로필 확인', 'Profil prüfen', 'Vérifier votre profil', 'Revisa tu perfil', '确认资料', 'Confira seu perfil', 'Controlla il profilo', 'Проверьте профиль'],
  'ob4.prD': ['Xから取得した表示名とアイコンです。内容はXの更新に合わせて自動で反映されます。', 'Display name and icon taken from X. They update automatically with X.', 'X에서 가져온 표시 이름과 아이콘입니다. X의 변경에 맞춰 자동 반영됩니다.', 'Anzeigename und Icon von X. Sie werden automatisch mit X aktualisiert.', 'Nom et icône issus de X, mis à jour automatiquement.', 'Nombre e icono obtenidos de X. Se actualizan automáticamente.', '来自 X 的显示名称和头像，会随 X 自动更新。', 'Nome e ícone obtidos do X. Atualizam automaticamente.', 'Nome e icona presi da X, aggiornati automaticamente.', 'Имя и значок из X. Обновляются автоматически вместе с X.'],
  'ob4.lkT': ['テーマとカラー', 'Theme & color', '테마와 색상', 'Design & Farbe', 'Thème et couleur', 'Tema y color', '主题与颜色', 'Tema e cor', 'Tema e colore', 'Тема и цвет'],
  'ob4.lkD': ['好みの見た目を選んでください。あとからコマンドパレットや設定で変更できます。', 'Pick a look you like. Change it later from the command palette or Settings.', '원하는 스타일을 고르세요. 나중에 명령 팔레트나 설정에서 바꿀 수 있습니다.', 'Wähle dein Aussehen. Später über die Befehlspalette oder Einstellungen änderbar.', 'Choisissez un style. Modifiable plus tard via la palette ou les réglages.', 'Elige tu estilo. Puedes cambiarlo luego desde la paleta o Ajustes.', '选择喜欢的外观，之后可在命令面板或设置中更改。', 'Escolha o visual. Altere depois pela paleta de comandos ou configurações.', 'Scegli l’aspetto. Modificabile poi da palette comandi o impostazioni.', 'Выберите внешний вид. Можно изменить позже через палитру команд или настройки.'],
  'ob4.lkLight': ['ライト', 'Light', '라이트', 'Hell', 'Clair', 'Claro', '浅色', 'Claro', 'Chiaro', 'Светлая'],
  'ob4.lkDark': ['ダーク', 'Dark', '다크', 'Dunkel', 'Sombre', 'Oscuro', '深色', 'Escuro', 'Scuro', 'Тёмная'],
})
