import { defineArea } from '../area'

// ログイン履歴・端末一覧(sec.*)
export default defineArea({
  'sec.tab': ['セキュリティ', 'Security', '보안', 'Sicherheit', 'Sécurité', 'Seguridad', '安全', 'Segurança', 'Sicurezza', 'Безопасность'],
  'sec.title': ['ログイン履歴と端末', 'Login history and devices', '로그인 기록 및 기기', 'Anmeldeverlauf und Geräte', 'Historique de connexion et appareils', 'Historial de inicio de sesión y dispositivos', '登录记录与设备', 'Histórico de login e dispositivos', 'Cronologia accessi e dispositivi', 'История входов и устройства'],
  'sec.desc': ['ログイン中の端末を確認し、心当たりのない端末をログアウトできます。新しい端末からログインするとメールでお知らせします。', 'Review signed-in devices and sign out any you do not recognize. You get an email when a new device signs in.', '로그인 중인 기기를 확인하고 모르는 기기는 로그아웃할 수 있습니다. 새 기기에서 로그인하면 메일로 알려 드립니다.', 'Sieh dir angemeldete Geräte an und melde unbekannte ab. Bei einer Anmeldung von einem neuen Gerät erhältst du eine E-Mail.', 'Consultez les appareils connectés et déconnectez ceux que vous ne reconnaissez pas. Un e-mail est envoyé lors d’une connexion depuis un nouvel appareil.', 'Revisa los dispositivos con sesión iniciada y cierra los que no reconozcas. Recibirás un correo cuando se inicie sesión desde un dispositivo nuevo.', '查看已登录的设备,并可退出不认识的设备。从新设备登录时会通过邮件通知你。', 'Veja os dispositivos conectados e saia dos que não reconhece. Você recebe um e-mail quando um novo dispositivo faz login.', 'Controlla i dispositivi connessi e disconnetti quelli che non riconosci. Riceverai un’e-mail quando accede un nuovo dispositivo.', 'Просматривайте устройства с активным входом и завершайте незнакомые сеансы. При входе с нового устройства придёт письмо.'],
  'sec.devices': ['ログイン中の端末', 'Signed-in devices', '로그인 중인 기기', 'Angemeldete Geräte', 'Appareils connectés', 'Dispositivos con sesión', '已登录的设备', 'Dispositivos conectados', 'Dispositivi connessi', 'Устройства с активным входом'],
  'sec.current': ['この端末', 'This device', '이 기기', 'Dieses Gerät', 'Cet appareil', 'Este dispositivo', '本设备', 'Este dispositivo', 'Questo dispositivo', 'Это устройство'],
  'sec.unknown': ['不明', 'Unknown', '알 수 없음', 'Unbekannt', 'Inconnu', 'Desconocido', '未知', 'Desconhecido', 'Sconosciuto', 'Неизвестно'],
  'sec.logout': ['ログアウト', 'Sign out', '로그아웃', 'Abmelden', 'Déconnecter', 'Cerrar sesión', '退出', 'Sair', 'Disconnetti', 'Выйти'],
  'sec.logoutOthers': ['他の端末をすべてログアウト', 'Sign out all other devices', '다른 기기 모두 로그아웃', 'Alle anderen Geräte abmelden', 'Déconnecter tous les autres appareils', 'Cerrar sesión en los demás dispositivos', '退出其他所有设备', 'Sair de todos os outros dispositivos', 'Disconnetti tutti gli altri dispositivi', 'Выйти на всех других устройствах'],
  'sec.logoutOthersQ': ['この端末以外をすべてログアウトしますか?', 'Sign out every device except this one?', '이 기기를 제외한 모든 기기를 로그아웃할까요?', 'Alle Geräte außer diesem abmelden?', 'Déconnecter tous les appareils sauf celui-ci ?', '¿Cerrar sesión en todos los dispositivos excepto este?', '要退出除本设备以外的所有设备吗?', 'Sair de todos os dispositivos, exceto este?', 'Disconnettere tutti i dispositivi tranne questo?', 'Выйти на всех устройствах, кроме этого?'],
  'sec.revoked': ['ログアウトしました', 'Signed out', '로그아웃했습니다', 'Abgemeldet', 'Déconnecté', 'Sesión cerrada', '已退出', 'Sessão encerrada', 'Disconnesso', 'Сеанс завершён'],
  'sec.history': ['最近のログイン', 'Recent logins', '최근 로그인', 'Letzte Anmeldungen', 'Connexions récentes', 'Inicios de sesión recientes', '最近登录', 'Logins recentes', 'Accessi recenti', 'Недавние входы'],
  'sec.historyEmpty': ['履歴はまだありません', 'No history yet', '아직 기록이 없습니다', 'Noch kein Verlauf', 'Aucun historique', 'Aún no hay historial', '暂无记录', 'Sem histórico ainda', 'Nessuna cronologia', 'Истории пока нет'],
  'sec.newDevice': ['新しい端末', 'New device', '새 기기', 'Neues Gerät', 'Nouvel appareil', 'Dispositivo nuevo', '新设备', 'Novo dispositivo', 'Nuovo dispositivo', 'Новое устройство'],
  'sec.noInfo': ['情報なし(以前のログイン)', 'No info (earlier login)', '정보 없음(이전 로그인)', 'Keine Angabe (frühere Anmeldung)', 'Aucune info (connexion antérieure)', 'Sin datos (inicio anterior)', '无信息(此前登录)', 'Sem informações (login anterior)', 'Nessuna info (accesso precedente)', 'Нет данных (прежний вход)'],
})
