import { defineArea } from '../area'

// Xシェア文面(ページごと)。並び: ja, en, ko, de, fr, es, zh, pt, it, ru
export default defineArea({
  'st.graph': ['{{name}}さんの投稿グラフ📈 毎朝の積み重ねを見てみて！', "{{name}}'s posting graph 📈 See the daily streak!", '{{name}}님의 게시 그래프 📈 매일 아침의 기록을 확인해 보세요!', 'Das Posting-Diagramm von {{name}} 📈 Schau dir die tägliche Serie an!', 'Le graphique de {{name}} 📈 Découvrez sa série quotidienne !', 'El gráfico de {{name}} 📈 ¡Mira su racha diaria!', '{{name}}的发帖图表📈 来看看每天的坚持！', 'O gráfico de {{name}} 📈 Veja a sequência diária!', 'Il grafico di {{name}} 📈 Guarda la serie giornaliera!', 'График {{name}} 📈 Посмотри ежедневную серию!'],
  'st.gallery': ['{{name}}さんの画像ギャラリー🖼️', "{{name}}'s image gallery 🖼️", '{{name}}님의 이미지 갤러리 🖼️', 'Die Bildergalerie von {{name}} 🖼️', 'La galerie de {{name}} 🖼️', 'La galería de {{name}} 🖼️', '{{name}}的图片画廊🖼️', 'A galeria de {{name}} 🖼️', 'La galleria di {{name}} 🖼️', 'Галерея {{name}} 🖼️'],
  'st.recap': ['{{name}}さんのおはツイ振り返り🎉', "{{name}}'s Ohatwi recap 🎉", '{{name}}님의 오하트윗 회고 🎉', 'Der Ohatwi-Rückblick von {{name}} 🎉', 'Le récap Ohatwi de {{name}} 🎉', 'El resumen Ohatwi de {{name}} 🎉', '{{name}}的Ohatwi回顾🎉', 'O resumo Ohatwi de {{name}} 🎉', 'Il recap Ohatwi di {{name}} 🎉', 'Итоги Ohatwi у {{name}} 🎉'],
  'st.folder': ['{{name}}さんのおはツイをフォルダ別に見る📁', "{{name}}'s Ohatwi by folder 📁", '{{name}}님의 오하트윗을 폴더별로 보기 📁', 'Ohatwi von {{name}} nach Ordnern 📁', "L'Ohatwi de {{name}} par dossier 📁", 'Ohatwi de {{name}} por carpetas 📁', '按文件夹查看{{name}}的Ohatwi📁', 'Ohatwi de {{name}} por pastas 📁', "L'Ohatwi di {{name}} per cartelle 📁", 'Ohatwi {{name}} по папкам 📁'],
  'st.ranking': ['おはツイKeeperのランキング🏆 みんなの継続記録をチェック！', 'Ohatwi Keeper rankings 🏆 Check everyone\'s streaks!', '오하트윗 Keeper 랭킹 🏆 모두의 연속 기록을 확인하세요!', 'Ohatwi-Keeper-Rangliste 🏆 Sieh dir alle Serien an!', 'Classement Ohatwi Keeper 🏆 Découvrez les séries de tous !', 'Ranking de Ohatwi Keeper 🏆 ¡Mira las rachas de todos!', 'Ohatwi Keeper排行榜🏆 看看大家的连续记录！', 'Ranking do Ohatwi Keeper 🏆 Veja as sequências de todos!', 'Classifica di Ohatwi Keeper 🏆 Guarda le serie di tutti!', 'Рейтинг Ohatwi Keeper 🏆 Смотри серии всех!'],
  'st.search': ['おはツイKeeperで過去のおはツイを検索🔍', 'Search past Ohatwis on Ohatwi Keeper 🔍', '오하트윗 Keeper에서 지난 오하트윗 검색 🔍', 'Alte Ohatwis in Ohatwi Keeper suchen 🔍', 'Rechercher d\'anciens Ohatwi sur Ohatwi Keeper 🔍', 'Busca Ohatwis antiguos en Ohatwi Keeper 🔍', '在Ohatwi Keeper搜索过去的Ohatwi🔍', 'Pesquise Ohatwis antigos no Ohatwi Keeper 🔍', 'Cerca vecchi Ohatwi su Ohatwi Keeper 🔍', 'Ищи старые Ohatwi в Ohatwi Keeper 🔍'],
  'st.diff': ['おはツイKeeperで2人の記録を比べてみた⚔️', 'Comparing two people\'s records on Ohatwi Keeper ⚔️', '오하트윗 Keeper로 두 사람의 기록을 비교해 봤어요 ⚔️', 'Zwei Verläufe in Ohatwi Keeper verglichen ⚔️', 'Comparaison de deux parcours sur Ohatwi Keeper ⚔️', 'Comparando dos registros en Ohatwi Keeper ⚔️', '用Ohatwi Keeper比较了两个人的记录⚔️', 'Comparando dois registros no Ohatwi Keeper ⚔️', 'Confronto tra due record su Ohatwi Keeper ⚔️', 'Сравнил два рекорда в Ohatwi Keeper ⚔️'],
  'st.survey': ['おはツイKeeperのアンケート📊 ぜひ回答・結果をチェック！', 'Ohatwi Keeper survey 📊 Take part and see the results!', '오하트윗 Keeper 설문 📊 참여하고 결과를 확인하세요!', 'Ohatwi-Keeper-Umfrage 📊 Mach mit und sieh die Ergebnisse!', 'Sondage Ohatwi Keeper 📊 Participez et voyez les résultats !', 'Encuesta de Ohatwi Keeper 📊 ¡Participa y mira los resultados!', 'Ohatwi Keeper问卷📊 来参与并查看结果！', 'Pesquisa do Ohatwi Keeper 📊 Participe e veja os resultados!', 'Sondaggio di Ohatwi Keeper 📊 Partecipa e guarda i risultati!', 'Опрос Ohatwi Keeper 📊 Участвуй и смотри результаты!'],
  'st.guide': ['おはツイKeeperの使い方・ツール📘 毎朝の記録がもっと楽しくなる！', 'How to use Ohatwi Keeper & tools 📘 Make your morning habit more fun!', '오하트윗 Keeper 사용법·도구 📘 매일 아침 기록이 더 즐거워져요!', 'Ohatwi Keeper: Anleitung & Tools 📘 Mehr Spaß an der Morgenroutine!', 'Ohatwi Keeper : guide et outils 📘 Rendez votre routine plus fun !', 'Ohatwi Keeper: guía y herramientas 📘 ¡Haz más divertida tu rutina!', 'Ohatwi Keeper使用指南与工具📘 让每天早上的记录更有趣！', 'Ohatwi Keeper: guia e ferramentas 📘 Deixe sua rotina mais divertida!', 'Ohatwi Keeper: guida e strumenti 📘 Rendi più divertente la routine!', 'Ohatwi Keeper: руководство и инструменты 📘 Сделай утреннюю привычку веселее!'],
  'st.patch': ['おはツイKeeperのアップデート履歴🆕 新機能をチェック！', 'Ohatwi Keeper update history 🆕 Check out the new features!', '오하트윗 Keeper 업데이트 내역 🆕 새 기능을 확인하세요!', 'Ohatwi-Keeper-Updates 🆕 Entdecke die neuen Funktionen!', 'Mises à jour d\'Ohatwi Keeper 🆕 Découvrez les nouveautés !', 'Novedades de Ohatwi Keeper 🆕 ¡Descubre las nuevas funciones!', 'Ohatwi Keeper更新记录🆕 来看看新功能！', 'Atualizações do Ohatwi Keeper 🆕 Veja as novidades!', 'Aggiornamenti di Ohatwi Keeper 🆕 Scopri le novità!', 'Обновления Ohatwi Keeper 🆕 Смотри новые функции!'],
  'st.home': ['おはツイKeeper ☀️ 毎朝のおはツイを記録して、継続を見える化！', 'Ohatwi Keeper ☀️ Log your morning posts and visualize your streak!', '오하트윗 Keeper ☀️ 매일 아침 기록을 남기고 연속 기록을 확인하세요!', 'Ohatwi Keeper ☀️ Halte deine Morgenposts fest und mach deine Serie sichtbar!', 'Ohatwi Keeper ☀️ Enregistrez vos posts du matin et visualisez votre série !', 'Ohatwi Keeper ☀️ ¡Registra tus posts matutinos y visualiza tu racha!', 'Ohatwi Keeper☀️ 记录每天早上的推文，让坚持看得见！', 'Ohatwi Keeper ☀️ Registre seus posts matinais e visualize sua sequência!', 'Ohatwi Keeper ☀️ Registra i post del mattino e visualizza la tua serie!', 'Ohatwi Keeper ☀️ Записывай утренние посты и наблюдай за серией!'],
})
